#!/bin/bash
#
#
# ./kalibr_events <IMAGER_BAG> <IMU_BAG>
#
#

IMAGER_BAG=$1
TARGET=$2
CAMCHAIN="${IMAGER_BAG%.bag}-camchain.yaml"

# Check if target is empty, and replace it with aprilgrid.yaml
if [ -z "$TARGET" ]; then
  echo "No target specified, using aprilgrid.yaml"
  TARGET=aprilgrid.yaml
fi

if [ -f "$CAMCHAIN" ]; then
  echo "$CAMCHAIN exists - please remove to rerun"
else
  export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1035
  rosrun kalibr kalibr_calibrate_cameras \
        --bag "$IMAGER_BAG" --target "$TARGET" \
        --models pinhole-radtan pinhole-radtan pinhole-radtan pinhole-radtan pinhole-radtan \
        --topics /prophesee/left/events /prophesee/right/events /ovc/left/image_mono/compressed /ovc/right/image_mono/compressed /ovc/rgb/image_color/compressed \
        --dont-show-report
fi
